org: implementing
service: hello-world-lambda

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-2

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          method: GET
          path: /hello
